In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
with open('messy_IMDB_dataset.csv', 'r', encoding='latin1') as f:
    for i in range(10):
        print(f"{i+1}: {f.readline()}")

1: IMBD title ID;Original titlÊ;Release year;Genrë¨;Duration;Country;Content Rating;Director;;Income; Votes ;Score

2: tt0111161;The Shawshank Redemption;1995-02-10;Drama;142;USA;R;Frank Darabont;;$ 28815245;2.278.845;9.3

3: tt0068646;The Godfather;09 21 1972;Crime, Drama;175;USA;R;Francis Ford Coppola;;$ 246120974;1.572.674;9.2

4: tt0468569;The Dark Knight; 23 -07-2008;Action, Crime, Drama;152;US;PG-13;Christopher Nolan;;$ 1005455211;2.241.615;9.

5: tt0071562;The Godfather: Part II;1975-09-25;Crime, Drama;220;USA;R;Francis Ford Coppola;;$ 4o8,035,783;1.098.714;9,.0

6: tt0110912;Pulp Fiction;1994-10-28;Crime, Drama; ;USA;R;Quentin Tarantino;;$ 222831817;1.780.147;8,9f

7: tt0167260;The Lord of the Rings: The Return of the King;22 Feb 04;Action, Adventure, Drama;201;New Zealand;PG-13;Peter Jackson;;$ 1142271098;1.604.280;08.9

8: tt0108052;Schindler's List;1994-03-11;Biography, Drama, History;Nan;USA;R;Steven Spielberg;;$ 322287794;1.183.248;8.9

9: tt0050083;12 Angry Men;1957-09-04;Crime, Drama;96;USA;Not Rated;Sidney Lumet;;$ 576;668.473;8.9

10: tt1375666;Inception;2010-09-24;Action, Adventure, Sci-Fi;148;USA;PG-13;Christopher Nolan;;$ 869784991;2.002.816;8..8

In [3]:
data = pd.read_csv(
    'messy_IMDB_dataset.csv',
    sep=';',
    encoding='latin1'
)

In [4]:
data.head()

,IMBD title ID,Original titlÊ,Release year,Genrë¨,Duration,Country,Content Rating,Director,Unnamed: 8,Income,Votes,Score
0,tt0111161,The Shawshank Redemption,1995-02-10,Drama,142,USA,R,Frank Darabont,NaN,$ 28815245,2.278.845,9.3
1,tt0068646,The Godfather,09 21 1972,"Crime, Drama",175,USA,R,Francis Ford Coppola,NaN,$ 246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,23 -07-2008,"Action, Crime, Drama",152,US,PG-13,Christopher Nolan,NaN,$ 1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975-09-25,"Crime, Drama",220,USA,R,Francis Ford Coppola,NaN,"$ 4o8,035,783",1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994-10-28,"Crime, Drama",,USA,R,Quentin Tarantino,NaN,$ 222831817,1.780.147,"8,9f"

In [5]:
data.isna().sum()

IMBD title ID       1
Original titlÊ      1
Release year        1
Genrë¨              1
Duration            2
Country             1
Content Rating     24
Director            1
Unnamed: 8        101
Income              1
 Votes              1
Score               1
dtype: int64

In [6]:
data.duplicated().sum()

np.int64(0)

In [7]:
data.columns

Index(['IMBD title ID', 'Original titlÊ', 'Release year', 'Genrë¨', 'Duration',
       'Country', 'Content Rating', 'Director', 'Unnamed: 8', 'Income',
       ' Votes ', 'Score'],
      dtype='object')

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   IMBD title ID   100 non-null    object
 1   Original titlÊ  100 non-null    object
 2   Release year    100 non-null    object
 3   Genrë¨          100 non-null    object
 4   Duration        99 non-null     object
 5   Country         100 non-null    object
 6   Content Rating  77 non-null     object
 7   Director        100 non-null    object
 8   Unnamed: 8      0 non-null      float64
 9   Income          100 non-null    object
 10   Votes          100 non-null    object
 11  Score           100 non-null    object
dtypes: float64(1), object(11)
memory usage: 9.6+ KB

In [10]:
data['Unnamed: 8']

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
96    NaN
97    NaN
98    NaN
99    NaN
100   NaN
Name: Unnamed: 8, Length: 101, dtype: float64

In [12]:
data = data.drop(columns='Unnamed: 8')

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   IMBD title ID   100 non-null    object
 1   Original titlÊ  100 non-null    object
 2   Release year    100 non-null    object
 3   Genrë¨          100 non-null    object
 4   Duration        99 non-null     object
 5   Country         100 non-null    object
 6   Content Rating  77 non-null     object
 7   Director        100 non-null    object
 8   Income          100 non-null    object
 9    Votes          100 non-null    object
 10  Score           100 non-null    object
dtypes: object(11)
memory usage: 8.8+ KB

In [14]:
data.head()

,IMBD title ID,Original titlÊ,Release year,Genrë¨,Duration,Country,Content Rating,Director,Income,Votes,Score
0,tt0111161,The Shawshank Redemption,1995-02-10,Drama,142,USA,R,Frank Darabont,$ 28815245,2.278.845,9.3
1,tt0068646,The Godfather,09 21 1972,"Crime, Drama",175,USA,R,Francis Ford Coppola,$ 246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,23 -07-2008,"Action, Crime, Drama",152,US,PG-13,Christopher Nolan,$ 1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975-09-25,"Crime, Drama",220,USA,R,Francis Ford Coppola,"$ 4o8,035,783",1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994-10-28,"Crime, Drama",,USA,R,Quentin Tarantino,$ 222831817,1.780.147,"8,9f"