In [1263]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [1264]:
with open('messy_IMDB_dataset.csv', 'r', encoding='latin1') as f:
    for i in range(10):
        print(f"{i+1}: {f.readline()}")

1: IMBD title ID;Original titlÊ;Release year;Genrë¨;Duration;Country;Content Rating;Director;;Income; Votes ;Score

2: tt0111161;The Shawshank Redemption;1995-02-10;Drama;142;USA;R;Frank Darabont;;$ 28815245;2.278.845;9.3

3: tt0068646;The Godfather;09 21 1972;Crime, Drama;175;USA;R;Francis Ford Coppola;;$ 246120974;1.572.674;9.2

4: tt0468569;The Dark Knight; 23 -07-2008;Action, Crime, Drama;152;US;PG-13;Christopher Nolan;;$ 1005455211;2.241.615;9.

5: tt0071562;The Godfather: Part II;1975-09-25;Crime, Drama;220;USA;R;Francis Ford Coppola;;$ 4o8,035,783;1.098.714;9,.0

6: tt0110912;Pulp Fiction;1994-10-28;Crime, Drama; ;USA;R;Quentin Tarantino;;$ 222831817;1.780.147;8,9f

7: tt0167260;The Lord of the Rings: The Return of the King;22 Feb 04;Action, Adventure, Drama;201;New Zealand;PG-13;Peter Jackson;;$ 1142271098;1.604.280;08.9

8: tt0108052;Schindler's List;1994-03-11;Biography, Drama, History;Nan;USA;R;Steven Spielberg;;$ 322287794;1.183.248;8.9

9: tt0050083;12 Angry Men;1957-09-04;Crime, Drama;96;USA;Not Rated;Sidney Lumet;;$ 576;668.473;8.9

10: tt1375666;Inception;2010-09-24;Action, Adventure, Sci-Fi;148;USA;PG-13;Christopher Nolan;;$ 869784991;2.002.816;8..8

In [1265]:
data = pd.read_csv(
    'messy_IMDB_dataset.csv',
    sep=';',
    encoding='latin1'
)

In [1266]:
data.head()

,IMBD title ID,Original titlÊ,Release year,Genrë¨,Duration,Country,Content Rating,Director,Unnamed: 8,Income,Votes,Score
0,tt0111161,The Shawshank Redemption,1995-02-10,Drama,142,USA,R,Frank Darabont,NaN,$ 28815245,2.278.845,9.3
1,tt0068646,The Godfather,09 21 1972,"Crime, Drama",175,USA,R,Francis Ford Coppola,NaN,$ 246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,23 -07-2008,"Action, Crime, Drama",152,US,PG-13,Christopher Nolan,NaN,$ 1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975-09-25,"Crime, Drama",220,USA,R,Francis Ford Coppola,NaN,"$ 4o8,035,783",1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994-10-28,"Crime, Drama",,USA,R,Quentin Tarantino,NaN,$ 222831817,1.780.147,"8,9f"

In [1267]:
data.isna().sum()

IMBD title ID       1
Original titlÊ      1
Release year        1
Genrë¨              1
Duration            2
Country             1
Content Rating     24
Director            1
Unnamed: 8        101
Income              1
 Votes              1
Score               1
dtype: int64

In [1268]:
data.duplicated().sum()

np.int64(0)

In [1269]:
data.columns

Index(['IMBD title ID', 'Original titlÊ', 'Release year', 'Genrë¨', 'Duration',
       'Country', 'Content Rating', 'Director', 'Unnamed: 8', 'Income',
       ' Votes ', 'Score'],
      dtype='object')

In [1270]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   IMBD title ID   100 non-null    object
 1   Original titlÊ  100 non-null    object
 2   Release year    100 non-null    object
 3   Genrë¨          100 non-null    object
 4   Duration        99 non-null     object
 5   Country         100 non-null    object
 6   Content Rating  77 non-null     object
 7   Director        100 non-null    object
 8   Unnamed: 8      0 non-null      float64
 9   Income          100 non-null    object
 10   Votes          100 non-null    object
 11  Score           100 non-null    object
dtypes: float64(1), object(11)
memory usage: 9.6+ KB

In [1271]:
data['Unnamed: 8']

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
96    NaN
97    NaN
98    NaN
99    NaN
100   NaN
Name: Unnamed: 8, Length: 101, dtype: float64

In [1272]:
data = data.drop(columns='Unnamed: 8')

In [1273]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   IMBD title ID   100 non-null    object
 1   Original titlÊ  100 non-null    object
 2   Release year    100 non-null    object
 3   Genrë¨          100 non-null    object
 4   Duration        99 non-null     object
 5   Country         100 non-null    object
 6   Content Rating  77 non-null     object
 7   Director        100 non-null    object
 8   Income          100 non-null    object
 9    Votes          100 non-null    object
 10  Score           100 non-null    object
dtypes: object(11)
memory usage: 8.8+ KB

In [1274]:
data.head()

,IMBD title ID,Original titlÊ,Release year,Genrë¨,Duration,Country,Content Rating,Director,Income,Votes,Score
0,tt0111161,The Shawshank Redemption,1995-02-10,Drama,142,USA,R,Frank Darabont,$ 28815245,2.278.845,9.3
1,tt0068646,The Godfather,09 21 1972,"Crime, Drama",175,USA,R,Francis Ford Coppola,$ 246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,23 -07-2008,"Action, Crime, Drama",152,US,PG-13,Christopher Nolan,$ 1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975-09-25,"Crime, Drama",220,USA,R,Francis Ford Coppola,"$ 4o8,035,783",1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994-10-28,"Crime, Drama",,USA,R,Quentin Tarantino,$ 222831817,1.780.147,"8,9f"

In [1275]:
data.isna().sum()

IMBD title ID      1
Original titlÊ     1
Release year       1
Genrë¨             1
Duration           2
Country            1
Content Rating    24
Director           1
Income             1
 Votes             1
Score              1
dtype: int64

In [1276]:
for col in data:
    print(data[col].unique())

['tt0111161' 'tt0068646' 'tt0468569' 'tt0071562' 'tt0110912' 'tt0167260'
 'tt0108052' 'tt0050083' 'tt1375666' 'tt0137523' 'tt0109830' 'tt0120737'
 'tt0060196' nan 'tt0133093' 'tt0167261' 'tt0080684' 'tt0099685'
 'tt0073486' 'tt0816692' 'tt0114369' 'tt0102926' 'tt0076759' 'tt0120815'
 'tt0120689' 'tt0317248' 'tt0245429' 'tt0118799' 'tt6751668' 'tt0038650'
 'tt0047478' 'tt0172495' 'tt0407887' 'tt0482571' 'tt0088763' 'tt0120586'
 'tt0110413' 'tt0103064' 'tt0114814' 'tt0110357' 'tt7286456' 'tt1675434'
 'tt0253474' 'tt2582802' 'tt0054215' 'tt0034583' 'tt0064116' 'tt0095327'
 'tt0095765' 'tt0027977' 'tt1345836' 'tt1853728' 'tt0209144' 'tt0910970'
 'tt0081505' 'tt0082971' 'tt4154756' 'tt0078748' 'tt4154796' 'tt0078788'
 'tt0364569' 'tt0057012' 'tt0047396' 'tt2380307' 'tt0405094' 'tt4633694'
 'tt1187043' 'tt0119698' 'tt0087843' 'tt0032553' 'tt0043014' 'tt0361748'
 'tt0169547' 'tt0112573' 'tt0086190' 'tt0105236' 'tt0338013' 'tt0114709'
 'tt0119217' 'tt0208092' 'tt0180093' 'tt0066921' 'tt0435761' 'tt0086250'
 'tt0075314' 'tt0211915' 'tt0093058' 'tt0090605' 'tt0062622' 'tt0033467'
 'tt8579674' 'tt0086879' 'tt0052357' 'tt0053125' 'tt2106476' 'tt0056172'
 'tt0070735' 'tt0082096' 'tt0059578' 'tt1832382' 'tt0045152']
['The Shawshank Redemption' 'The Godfather' 'The Dark Knight'
 'The Godfather: Part II' 'Pulp Fiction'
 'The Lord of the Rings: The Return of the King' "Schindler's List"
 '12 Angry Men' 'Inception' 'Fight Club' 'Forrest Gump'
 'The Lord of the Rings: The Fellowship of the Ring'
 'Il buono, il brutto, il cattivo' nan 'The Matrix'
 'The Lord of the Rings: The Two Towers'
 'Star Wars: Episode V - The Empire Strikes Back' 'Goodfellas'
 "One Flew Over the Cuckoo's Nest" 'Interstellar' 'Se7en'
 'The Silence of the Lambs' 'Star Wars' 'Saving Private Ryan'
 'The Green Mile' 'Cidade de Deus' 'Sen to Chihiro no kamikakushi'
 'La vita B9 bella' 'Gisaengchung' "It's a Wonderful Life"
 'Shichinin no samurai' 'Gladiator' 'The Departed' 'The Prestige'
 'Back to the Future' 'American History X' 'LÃ©on'
 'Terminator 2: Judgment Day' 'The Usual Suspects' 'The Lion King' 'Joker'
 'Intouchables' 'The Pianist' 'Whiplash' 'Psycho' 'Casablanca'
 "C'era una volta il West" 'Hotaru no haka' 'Nuovo Cinema Paradiso'
 'Modern Times' 'The Dark Knight Rises' 'Django Unchained' 'Memento'
 'WALLÂ·E' 'The Shining' 'Raiders of the Lost Ark'
 'Avengers: Infinity War' 'Alien' 'Avengers: Endgame' 'Apocalypse Now'
 'Oldeuboi'
 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb'
 'Rear Window' 'Coco' 'Das Leben der Anderen'
 'Spider-Man: Into the Spider-Verse' '3 Idiots' 'Mononoke-hime'
 'Once Upon a Time in America' 'The Great Dictator' 'Sunset Blvd.'
 'Inglourious Basterds' 'American Beauty' 'Braveheart'
 'Star Wars: Episode VI - Return of the Jedi' 'Reservoir Dogs'
 'Eternal Sunshine of the Spotless Mind' 'Toy Story' 'Good Will Hunting'
 'Snatch' 'Requiem for a Dream' 'A Clockwork Orange' 'Toy Story 3'
 'Scarface' 'Taxi Driver' "Le fabuleux destin d'AmÃ©lie Poulain"
 'Full Metal Jacket' 'Aliens' '2001: A Space Odyssey' 'Citizen Kane'
 '1917' 'Amadeus' 'Vertigo' 'North by Northwest' 'Jagten'
 'Lawrence of Arabia' 'The Sting' 'Das Boot' 'Per qualche dollaro in piÃ¹'
 'Jodaeiye Nader az Simin' "Singin' in the Rain"]
['1995-02-10' '09 21 1972' ' 23 -07-2008' '1975-09-25' '1994-10-28'
 '22 Feb 04' '1994-03-11' '1957-09-04' '2010-09-24' '10-29-99'
 '1994-10-06' '2002-01-18' '23rd December of 1966 ' nan '1999-05-07'
 '01/16-03' '1980-09-19' '1990-09-20' '18/11/1976' '2014-11-06'
 '1995-12-15' '1991-03-05' '1977-10-20' '1998-10-30' '2000-10-03'
 '2003-05-09' '2003-04-18' '1997-12-20' '2019-11-07' '1948-03-11'
 '1955-08-19' '2000-05-19' '2006-10-27' '2006-12-22' '1985-10-18'
 '1999-08-27' '1995-04-07' '1991-12-19' '1995-11-30' '1994-11-25'
 '2019-10-03' '2012-02-24' '2002-10-25' '2015-02-12' '1960-10-28'
 '21-11-46' '1968-12-21' '2015-10-11' '1988-11-17' '1937-03-12'
 '2012-08-29' '2013-01-17' '2001-01-19' '2008-10-17' '1980-12-22'
 '1981-06-12' '2018-04-25' '1979-10-25' '2019-04-24' '1979-12-18'
 '2005-05-06' '1964-04-03' '1955-04-14' '2017-12-28' '2007-04-06'
 '2018-12-25' '2009-12-25' '1984-09-28' '1945-06-25'
 'The 6th of marzo, year 1951' '2009-10-02' '2000-01-21' '1995-12-01'
 '1983-10-21' '1992-10-09' '2004-10-22' '1996-03-22' '1998-03-06'
 '2001-03-16' '2000-12-15' '1972-09-07' '2010-07-07' '1984-02-34'
 '1976-13-24' '2002-01-25' '1987-10-09' '1986-09-24' '1968-12-12'
 '1948-11-25' '2020-01-23' '1985-02-15' '1958-11-18' '1959-10-28'
 '2012-11-22' '1963-10-29' '1974-03-21' '1982-03-18' '1965-12-20'
 '2011-10-21' '1953-02-05']
['Drama' 'Crime, Drama' 'Action, Crime, Drama' 'Action, Adventure, Drama'
 'Biography, Drama, History' 'Action, Adventure, Sci-Fi' 'Drama, Romance'
 'Western' nan 'Action, Sci-Fi' 'Action, Adventure, Fantasy'
 'Biography, Crime, Drama' 'Adventure, Drama, Sci-Fi'
 'Crime, Drama, Mystery' 'Crime, Drama, Thriller' 'Drama, War'
 'Crime, Drama, Fantasy' 'Animation, Adventure, Family'
 'Comedy, Drama, Romance' 'Comedy, Drama, Thriller'
 'Drama, Family, Fantasy' 'Drama, Mystery, Sci-Fi'
 'Adventure, Comedy, Sci-Fi' 'Crime, Mystery, Thriller'
 'Animation, Adventure, Drama' 'Biography, Comedy, Drama'
 'Biography, Drama, Music' 'Drama, Music' 'Horror, Mystery, Thriller'
 'Drama, Romance, War' 'Animation, Drama, War' 'Comedy, Drama, Family'
 'Action, Adventure' 'Drama, Western' 'Mystery, Thriller' 'Drama, Horror'
 'Horror, Sci-Fi' 'Drama, Mystery, War' 'Action, Drama, Mystery' 'Comedy'
 'Drama, Mystery, Thriller' 'Animation, Action, Adventure' 'Comedy, Drama'
 'Animation, Adventure, Fantasy' 'Comedy, Drama, War' 'Drama, Film-Noir'
 'Adventure, Drama, War' 'Drama, Romance, Sci-Fi'
 'Animation, Adventure, Comedy' 'Comedy, Crime' 'Crime, Drama, Sci-Fi'
 'Comedy, Romance' 'Adventure, Sci-Fi' 'Drama, Mystery'
 'Mystery, Romance, Thriller' 'Adventure, Mystery, Thriller'
 'Adventure, Biography, Drama' 'Comedy, Crime, Drama'
 'Adventure, Drama, Thriller' 'Comedy, Musical, Romance']
['142' '175' '152' '220' ' ' '201' 'Nan' '96' '148' 'Inf' '178c' '161' nan
 '179' 'Not Applicable' '146' '-' '169' '127' '118' '121' '189' '130'
 '125' '116' '132' '207' '155' '151' '119' '110' '137' '106' '88' '122'
 '112' '150' '109' '102' '165' '89' '87' '164' '113' '98' '115' '149'
 '117' '181' '147' '120' '95' '105' '170' '134' '229' '153' '178' '131'
 '99' '108' '81' '126' '104' '136' '103' '114' '160' '128' '228' '129'
 '123']
['USA' 'US' 'New Zealand' 'UK' 'New Zesland' 'Italy' nan 'New Zeland'
 'US.' 'Brazil' 'Japan' 'Italy1' 'South Korea' 'France' 'Germany' 'India'
 'Denmark' 'West Germany' 'Iran']
['R' 'PG-13' 'Not Rated' 'Approved' nan 'PG' 'Unrated' 'G']
['Frank Darabont' 'Francis Ford Coppola' 'Christopher Nolan'
 'Quentin Tarantino' 'Peter Jackson' 'Steven Spielberg' 'Sidney Lumet'
 'David Fincher' 'Robert Zemeckis' 'Sergio Leone' nan
 'Lana Wachowski, Lilly Wachowski' 'Irvin Kershner' 'Martin Scorsese'
 'Milos Forman' 'Jonathan Demme' 'George Lucas'
 'Fernando Meirelles, KÃ¡tia Lund' 'Hayao Miyazaki' 'Roberto Benigni'
 'Bong Joon Ho' 'Frank Capra' 'Akira Kurosawa' 'Ridley Scott' 'Tony Kaye'
 'Luc Besson' 'James Cameron' 'Bryan Singer' 'Roger Allers, Rob Minkoff'
 'Todd Phillips' 'Olivier Nakache, Ã\x89ric Toledano' 'Roman Polanski'
 'Damien Chazelle' 'Alfred Hitchcock' 'Michael Curtiz' 'Isao Takahata'
 'Giuseppe Tornatore' 'Charles Chaplin' 'Andrew Stanton' 'Stanley Kubrick'
 'Anthony Russo, Joe Russo' 'Chan-wook Park' 'Lee Unkrich, Adrian Molina'
 'Florian Henckel von Donnersmarck' 'Bob Persichetti, Peter Ramsey'
 'Rajkumar Hirani' 'Billy Wilder' 'Sam Mendes' 'Mel Gibson'
 'Richard Marquand' 'Michel Gondry' 'John Lasseter' 'Gus Van Sant'
 'Guy Ritchie' 'Darren Aronofsky' 'Lee Unkrich' 'Brian De Palma'
 'Jean-Pierre Jeunet' 'Orson Welles' 'Thomas Vinterberg' 'David Lean'
 'George Roy Hill' 'Wolfgang Petersen' 'Asghar Farhadi' 'Stanley Donen']
['$ 28815245' '$ 246120974' '$ 1005455211' '$ 4o8,035,783' '$ 222831817'
 '$ 1142271098' '$ 322287794' '$ 576' '$ 869784991' '$ 101218804'
 '$ 678229452' '$ 887934303' '$ 25252481' nan '$ 465718588' '$ 951227416'
 '$ 549265501' '$ 46879633' '$ 108997629' '$ 696742056' '$ 327333559'
 '$ 272753884' '$ 775768912' '$ 482349603' '$ 286801374' '$ 30680793'
 '$ 355467056' '$ 230098753' '$ 257604912' '$ 6130720' '$ 322773'
 '$ 465361176' '$ 291465034' '$ 109676311' '$ 388774684' '$ 23875127'
 '$ 19552639' '$ 520884847' '$ 23341568' '$ 968511805' '$ 1074251311'
 '$ 426588510' '$ 120072577' '$ 48983260' '$ 32008644' '$ 4374761'
 '$ 112911' '$ 516962' '$ 13826605' '$ 457688' '$ 1081133191'
 '$ 425368238' '$ 39970386' '$ 521311860' '$ 46520613' '$ 390133212'
 '$ 2048359754' '$ 108110316' '$ 2797800564' '$ 91968688' '$ 15002116'
 '$ 9443876' '$ 37032034' '$ 807083670' '$ 77356942' '$ 375540831'
 '$ 60262836' '$ 169785629' '$ 5472914' '$ 969879' '$ 299645'
 '$ 321455689' '$ 356296601' '$ 213216216' '$ 475347111' '$ 2889963'
 '$ 74036715' '$ 404265438' '$ 225933435' '$ 83557872' '$ 7390108'
 '$ 26903440' '$ 1066969703' '$ 66023585' '$ 28441292' '$ 173924742'
 '$ 46357676' '$ 131384634' '$ 68989547' '$ 1594107' '$ 384857224'
 '$ 52066791' '$ 7796389' '$ 73446' '$ 15843274' '$ 45710874'
 '$ 156000000' '$ 11487676' '$ 15000000' '$ 22926076' '$ 1864182']
['2.278.845' '1.572.674' '2.241.615' '1.098.714' '1.780.147' '1.604.280'
 '1.183.248' '668.473' '2.002.816' '1.807.440' '1.755.490' '1.619.920'
 '672.499' nan '1.632.315' '1.449.778' '1.132.073' '991.505' '891.071'
 '1.449.256' '1.402.015' '1.234.134' '1.204.107' '1.203.825' '1.112.336'
 '685.856' '626.693' '605.648' '470.931' '388.310' '307.958' '1.308.193'
 '1.159.703' '1.155.723' '1.027.330' '1.014.218' '1.007.598' '974.970'
 '968.947' '917.248' '855.097' '736.691' '707.942' '690.732' '586.765'
 '509.953' '295.220' '225.438' '223.050' '211.250' '1.480.582' '1.317.856'
 '1.098.879' '974.734' '869.480' '865.510' '796.486' '768.874' '754.786'
 '591.251' '501.082' '441.115' '432.390' '352.455' '349.642' '335.892'
 '332.217' '331.045' '302.317' '197.381' '195.789' '1.229.958' '1.049.009'
 '941.683' '928.036' '896.551' '889.875' '864.461' '837.379' '766.589'
 '748.291' '740.301' '739.717' '721.343' '703.264' '690.480' '658.175'
 '639.500' '587.866' '389.322' '362.897' '361.028' '352.786' '291.628'
 '269.616' '261.504' '236.285' '226.427' '226.039' '214.165' '213.152']
['9.3' '9.2' '9.' '9,.0' '8,9f' '08.9' '8.9' '8..8' '8.8' '8:8' nan
 '++8.7' '8.7.' '8,7e-0' '8.7' '8.6' '8,6' '8.5' '8.4' '8.3' '8.2' '8.1'
 '8.0' '7.9' '7.8' '7.7' '7.6' '7.5' '7.4']

- titleId - it has one missing values and the uniquq colum also looks good just adjust the white spaces
- Original Title - need to chanhge the column nname and has ine missing value and standardized the text
- release year - need to change the data time data type and there few inapproaitate terms before changin handle them 
    either drop them or change their format by using regex
- genre - remove white spaces and standarize the name drop that one null or fill with mode
- duration - has inf , - and c suffix and spaces remove those null values are 2 
- country - it has different format of same country and few spelling mistakes handle them
- Content rating - R' 'PG-13' 'Not Rated' 'Approved' nan 'PG' 'Unrated' 'G' handle just those null values
- director - remoce white spaces and handle them, to standardiezed
- Income - make sure you that it is in proper numeric format like there is o instead of 0 handle the missing values
- votes - it is not proper format of float
- score - it has different symbol and double .. so handle them few thery re starting with 08 and i see two ++ symbols

In [1277]:
df = data.copy()

In [1278]:
df.head()

,IMBD title ID,Original titlÊ,Release year,Genrë¨,Duration,Country,Content Rating,Director,Income,Votes,Score
0,tt0111161,The Shawshank Redemption,1995-02-10,Drama,142,USA,R,Frank Darabont,$ 28815245,2.278.845,9.3
1,tt0068646,The Godfather,09 21 1972,"Crime, Drama",175,USA,R,Francis Ford Coppola,$ 246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,23 -07-2008,"Action, Crime, Drama",152,US,PG-13,Christopher Nolan,$ 1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975-09-25,"Crime, Drama",220,USA,R,Francis Ford Coppola,"$ 4o8,035,783",1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994-10-28,"Crime, Drama",,USA,R,Quentin Tarantino,$ 222831817,1.780.147,"8,9f"

titleId - it has one missing values and the uniquq colum also looks good just adjust the white spaces

In [1279]:
df['IMBD title ID'].isna().sum()

np.int64(1)

In [1280]:
df[df['IMBD title ID'].isna()]

,IMBD title ID,Original titlÊ,Release year,Genrë¨,Duration,Country,Content Rating,Director,Income,Votes,Score
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1281]:
df = df.dropna(subset='IMBD title ID')
df['IMBD title ID'].isna().sum()

np.int64(0)

In [1282]:
df[df['IMBD title ID'].isna()]

Empty DataFrame
Columns: [IMBD title ID, Original titlÊ, Release year, Genrë¨, Duration, Country, Content Rating, Director, Income,  Votes , Score]
Index: []

In [1283]:
df['IMBD title ID'] = df['IMBD title ID'].str.strip()

Original Title - need to chanhge the column nname and has missing value and standardized the text

In [1284]:
df = df.rename(columns ={"Original titlÊ" : "Original Title"})

In [1285]:
df.isna().sum()

IMBD title ID      0
Original Title     0
Release year       0
Genrë¨             0
Duration           1
Country            0
Content Rating    23
Director           0
Income             0
 Votes             0
Score              0
dtype: int64

In [1286]:
df['Original Title'] = df['Original Title'].str.strip()

In [1287]:
df['Original Title'].unique()

array(['The Shawshank Redemption', 'The Godfather', 'The Dark Knight',
       'The Godfather: Part II', 'Pulp Fiction',
       'The Lord of the Rings: The Return of the King',
       "Schindler's List", '12 Angry Men', 'Inception', 'Fight Club',
       'Forrest Gump',
       'The Lord of the Rings: The Fellowship of the Ring',
       'Il buono, il brutto, il cattivo', 'The Matrix',
       'The Lord of the Rings: The Two Towers',
       'Star Wars: Episode V - The Empire Strikes Back', 'Goodfellas',
       "One Flew Over the Cuckoo's Nest", 'Interstellar', 'Se7en',
       'The Silence of the Lambs', 'Star Wars', 'Saving Private Ryan',
       'The Green Mile', 'Cidade de Deus',
       'Sen to Chihiro no kamikakushi', 'La vita B9 bella',
       'Gisaengchung', "It's a Wonderful Life", 'Shichinin no samurai',
       'Gladiator', 'The Departed', 'The Prestige', 'Back to the Future',
       'American History X', 'LÃ©on', 'Terminator 2: Judgment Day',
       'The Usual Suspects', 'The Lion King', 'Joker', 'Intouchables',
       'The Pianist', 'Whiplash', 'Psycho', 'Casablanca',
       "C'era una volta il West", 'Hotaru no haka',
       'Nuovo Cinema Paradiso', 'Modern Times', 'The Dark Knight Rises',
       'Django Unchained', 'Memento', 'WALLÂ·E', 'The Shining',
       'Raiders of the Lost Ark', 'Avengers: Infinity War', 'Alien',
       'Avengers: Endgame', 'Apocalypse Now', 'Oldeuboi',
       'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
       'Rear Window', 'Coco', 'Das Leben der Anderen',
       'Spider-Man: Into the Spider-Verse', '3 Idiots', 'Mononoke-hime',
       'Once Upon a Time in America', 'The Great Dictator',
       'Sunset Blvd.', 'Inglourious Basterds', 'American Beauty',
       'Braveheart', 'Star Wars: Episode VI - Return of the Jedi',
       'Reservoir Dogs', 'Eternal Sunshine of the Spotless Mind',
       'Toy Story', 'Good Will Hunting', 'Snatch', 'Requiem for a Dream',
       'A Clockwork Orange', 'Toy Story 3', 'Scarface', 'Taxi Driver',
       "Le fabuleux destin d'AmÃ©lie Poulain", 'Full Metal Jacket',
       'Aliens', '2001: A Space Odyssey', 'Citizen Kane', '1917',
       'Amadeus', 'Vertigo', 'North by Northwest', 'Jagten',
       'Lawrence of Arabia', 'The Sting', 'Das Boot',
       'Per qualche dollaro in piÃ¹', 'Jodaeiye Nader az Simin',
       "Singin' in the Rain"], dtype=object)

release year - need to change the data time data type and there few inapproaitate terms before changin handle them 
    either drop them or change their format by using regex

In [1288]:
# df['Release year'] = pd.to_datetime(df['Release year'])

In [1289]:
df['Release year'].unique()

array(['1995-02-10', '09 21 1972', ' 23 -07-2008', '1975-09-25',
       '1994-10-28', '22 Feb 04', '1994-03-11', '1957-09-04',
       '2010-09-24', '10-29-99', '1994-10-06', '2002-01-18',
       '23rd December of 1966 ', '1999-05-07', '01/16-03', '1980-09-19',
       '1990-09-20', '18/11/1976', '2014-11-06', '1995-12-15',
       '1991-03-05', '1977-10-20', '1998-10-30', '2000-10-03',
       '2003-05-09', '2003-04-18', '1997-12-20', '2019-11-07',
       '1948-03-11', '1955-08-19', '2000-05-19', '2006-10-27',
       '2006-12-22', '1985-10-18', '1999-08-27', '1995-04-07',
       '1991-12-19', '1995-11-30', '1994-11-25', '2019-10-03',
       '2012-02-24', '2002-10-25', '2015-02-12', '1960-10-28', '21-11-46',
       '1968-12-21', '2015-10-11', '1988-11-17', '1937-03-12',
       '2012-08-29', '2013-01-17', '2001-01-19', '2008-10-17',
       '1980-12-22', '1981-06-12', '2018-04-25', '1979-10-25',
       '2019-04-24', '1979-12-18', '2005-05-06', '1964-04-03',
       '1955-04-14', '2017-12-28', '2007-04-06', '2018-12-25',
       '2009-12-25', '1984-09-28', '1945-06-25',
       'The 6th of marzo, year 1951', '2009-10-02', '2000-01-21',
       '1995-12-01', '1983-10-21', '1992-10-09', '2004-10-22',
       '1996-03-22', '1998-03-06', '2001-03-16', '2000-12-15',
       '1972-09-07', '2010-07-07', '1984-02-34', '1976-13-24',
       '2002-01-25', '1987-10-09', '1986-09-24', '1968-12-12',
       '1948-11-25', '2020-01-23', '1985-02-15', '1958-11-18',
       '1959-10-28', '2012-11-22', '1963-10-29', '1974-03-21',
       '1982-03-18', '1965-12-20', '2011-10-21', '1953-02-05'],
      dtype=object)

In [1290]:
small_data ={ "Date" : ["The 6th of marco, year 1951","23 -07-2008","23rd December of 1966","22 Feb 04","2011-10-21" , "21-11-46" , "01/16-03","22 Feb 04","23rd December of 1966",]}
df_new = pd.DataFrame(small_data)

In [1291]:
df_new

                          Date
0  The 6th of marco, year 1951
1                  23 -07-2008
2        23rd December of 1966
3                    22 Feb 04
4                   2011-10-21
5                     21-11-46
6                     01/16-03
7                    22 Feb 04
8        23rd December of 1966

In [1292]:
from dateutil.parser import parse

In [1293]:
from calendar import monthrange
df_new = df_new["Date"].apply( lambda x : parse(x ,fuzzy=True) )
s = "1984-02-34"
parts = s.split("-")
print(parts)

['1984', '02', '34']

In [1294]:
from datetime import datetime


def fix_country(d):
    if pd.isna(d):
        return d
    if d.year > datetime.now().year:
        d = d.replace(year = d.year - 100)
    return d

In [1295]:
df_new = df_new.apply(fix_country)

In [1296]:
df_new

0   1951-06-15
1   2008-07-23
2   1966-12-23
3   2004-02-22
4   2011-10-21
5   1946-11-21
6   2003-01-16
7   2004-02-22
8   1966-12-23
Name: Date, dtype: datetime64[ns]

In [1297]:
def safe_parse(s):
    try:
        return parse(s,fuzzy=True)
    except(ValueError,OverflowError):
        return pd.NaT

In [1298]:
df["Release year"] = df["Release year"].apply(safe_parse)
df["Release year"] = df["Release year"].apply(fix_country)

In [1299]:
df["Release year"].unique()

<DatetimeArray>
['1995-02-10 00:00:00', '1972-09-21 00:00:00', '2008-07-23 00:00:00',
 '1975-09-25 00:00:00', '1994-10-28 00:00:00', '2004-02-22 00:00:00',
 '1994-03-11 00:00:00', '1957-09-04 00:00:00', '2010-09-24 00:00:00',
 '1999-10-29 00:00:00', '1994-10-06 00:00:00', '2002-01-18 00:00:00',
 '1966-12-23 00:00:00', '1999-05-07 00:00:00', '2003-01-16 00:00:00',
 '1980-09-19 00:00:00', '1990-09-20 00:00:00', '1976-11-18 00:00:00',
 '2014-11-06 00:00:00', '1995-12-15 00:00:00', '1991-03-05 00:00:00',
 '1977-10-20 00:00:00', '1998-10-30 00:00:00', '2000-10-03 00:00:00',
 '2003-05-09 00:00:00', '2003-04-18 00:00:00', '1997-12-20 00:00:00',
 '2019-11-07 00:00:00', '1948-03-11 00:00:00', '1955-08-19 00:00:00',
 '2000-05-19 00:00:00', '2006-10-27 00:00:00', '2006-12-22 00:00:00',
 '1985-10-18 00:00:00', '1999-08-27 00:00:00', '1995-04-07 00:00:00',
 '1991-12-19 00:00:00', '1995-11-30 00:00:00', '1994-11-25 00:00:00',
 '2019-10-03 00:00:00', '2012-02-24 00:00:00', '2002-10-25 00:00:00',
 '2015-02-12 00:00:00', '1960-10-28 00:00:00', '1946-11-21 00:00:00',
 '1968-12-21 00:00:00', '2015-10-11 00:00:00', '1988-11-17 00:00:00',
 '1937-03-12 00:00:00', '2012-08-29 00:00:00', '2013-01-17 00:00:00',
 '2001-01-19 00:00:00', '2008-10-17 00:00:00', '1980-12-22 00:00:00',
 '1981-06-12 00:00:00', '2018-04-25 00:00:00', '1979-10-25 00:00:00',
 '2019-04-24 00:00:00', '1979-12-18 00:00:00', '2005-05-06 00:00:00',
 '1964-04-03 00:00:00', '1955-04-14 00:00:00', '2017-12-28 00:00:00',
 '2007-04-06 00:00:00', '2018-12-25 00:00:00', '2009-12-25 00:00:00',
 '1984-09-28 00:00:00', '1945-06-25 00:00:00', '1951-06-15 00:00:00',
 '2009-10-02 00:00:00', '2000-01-21 00:00:00', '1995-12-01 00:00:00',
 '1983-10-21 00:00:00', '1992-10-09 00:00:00', '2004-10-22 00:00:00',
 '1996-03-22 00:00:00', '1998-03-06 00:00:00', '2001-03-16 00:00:00',
 '2000-12-15 00:00:00', '1972-09-07 00:00:00', '2010-07-07 00:00:00',
                 'NaT', '2002-01-25 00:00:00', '1987-10-09 00:00:00',
 '1986-09-24 00:00:00', '1968-12-12 00:00:00', '1948-11-25 00:00:00',
 '2020-01-23 00:00:00', '1985-02-15 00:00:00', '1958-11-18 00:00:00',
 '1959-10-28 00:00:00', '2012-11-22 00:00:00', '1963-10-29 00:00:00',
 '1974-03-21 00:00:00', '1982-03-18 00:00:00', '1965-12-20 00:00:00',
 '2011-10-21 00:00:00', '1953-02-05 00:00:00']
Length: 98, dtype: datetime64[ns]

In [1300]:
df[df['Release year'].isna()]

,IMBD title ID,Original Title,Release year,Genrë¨,Duration,Country,Content Rating,Director,Income,Votes,Score
83,tt0086250,Scarface,NaT,"Crime, Drama",170,USA,R,Brian De Palma,$ 66023585,721.343,7.8
84,tt0075314,Taxi Driver,NaT,"Crime, Drama",114,USA,R,Martin Scorsese,$ 28441292,703.264,7.7

genre - remove white spaces and standarize the name drop that one null or fill with mode

In [1301]:
df.columns

Index(['IMBD title ID', 'Original Title', 'Release year', 'Genrë¨', 'Duration',
       'Country', 'Content Rating', 'Director', 'Income', ' Votes ', 'Score'],
      dtype='object')

In [1302]:
df = df.rename(columns={'Genrë¨': 'Genre'})

In [1303]:
df.columns

Index(['IMBD title ID', 'Original Title', 'Release year', 'Genre', 'Duration',
       'Country', 'Content Rating', 'Director', 'Income', ' Votes ', 'Score'],
      dtype='object')

In [1304]:
df['Genre'] = df['Genre'].str.strip()

In [1305]:
df['Genre'].isna().sum()

np.int64(0)

duration - has inf , - and c suffix and spaces remove those null values are 2

In [1306]:
df['Duration'].unique()
# df['Duration'] = df['Duration'].str.strip()

array(['142', '175', '152', '220', ' ', '201', 'Nan', '96', '148', 'Inf',
       '178c', '161', nan, '179', 'Not Applicable', '146', '-', '169',
       '127', '118', '121', '189', '130', '125', '116', '132', '207',
       '155', '151', '119', '110', '137', '106', '88', '122', '112',
       '150', '109', '102', '165', '89', '87', '164', '113', '98', '115',
       '149', '117', '181', '147', '120', '95', '105', '170', '134',
       '229', '153', '178', '131', '99', '108', '81', '126', '104', '136',
       '103', '114', '160', '128', '228', '129', '123'], dtype=object)

In [1307]:
df['Duration'] = df['Duration'].replace(['Not Applicable',' ','-','Inf','Nan'] , np.nan)

In [1308]:
df['Duration'] = df['Duration'].str.replace('c' , '')
df['Duration'].unique()

array(['142', '175', '152', '220', nan, '201', '96', '148', '178', '161',
       '179', '146', '169', '127', '118', '121', '189', '130', '125',
       '116', '132', '207', '155', '151', '119', '110', '137', '106',
       '88', '122', '112', '150', '109', '102', '165', '89', '87', '164',
       '113', '98', '115', '149', '117', '181', '147', '120', '95', '105',
       '170', '134', '229', '153', '131', '99', '108', '81', '126', '104',
       '136', '103', '114', '160', '128', '228', '129', '123'],
      dtype=object)

In [1309]:
df['Duration'].isna().sum()

np.int64(6)

In [1310]:
df[df['Duration'].isna()]

,IMBD title ID,Original Title,Release year,Genre,Duration,Country,Content Rating,Director,Income,Votes,Score
4,tt0110912,Pulp Fiction,1994-10-28,"Crime, Drama",NaN,USA,R,Quentin Tarantino,$ 222831817,1.780.147,"8,9f"
6,tt0108052,Schindler's List,1994-03-11,"Biography, Drama, History",NaN,USA,R,Steven Spielberg,$ 322287794,1.183.248,8.9
9,tt0137523,Fight Club,1999-10-29,Drama,NaN,UK,R,David Fincher,$ 101218804,1.807.440,8.8
14,tt0133093,The Matrix,1999-05-07,"Action, Sci-Fi",NaN,USA,R,"Lana Wachowski, Lilly Wachowski",$ 465718588,1.632.315,++8.7
16,tt0080684,Star Wars: Episode V - The Empire Strikes Back,1980-09-19,"Action, Adventure, Fantasy",NaN,USA,PG,Irvin Kershner,$ 549265501,1.132.073,"8,7e-0"
18,tt0073486,One Flew Over the Cuckoo's Nest,1976-11-18,Drama,NaN,USA,R,Milos Forman,$ 108997629,891.071,8.7

In [1311]:
df = df.dropna(subset='Duration')
df[df['Duration'].isna()]

Empty DataFrame
Columns: [IMBD title ID, Original Title, Release year, Genre, Duration, Country, Content Rating, Director, Income,  Votes , Score]
Index: []

In [1312]:
df['Duration'] = df['Duration'].astype('int')

In [1313]:
df['Duration'].dtype

dtype('int64')

country - it has different format of same country and few spelling mistakes handle them

In [1314]:
df['Country'].unique()
df['Country'].value_counts()

Country
USA             57
UK              11
Italy            4
Japan            4
France           3
South Korea      2
Germany          2
West Germany     1
Denmark          1
India            1
Italy1           1
US               1
Brazil           1
US.              1
New Zeland       1
New Zesland      1
New Zealand      1
Iran             1
Name: count, dtype: int64

In [1315]:
fixes = {
    'New Zesland' : 'New Zealand',
    'New Zeland' : 'New Zealand',
    'US.' : 'USA',
    'US': 'USA'
}

df['Country'] = df['Country'].replace(fixes)

In [1316]:
df['Country'].unique()

array(['USA', 'New Zealand', 'Italy', 'Brazil', 'Japan', 'Italy1',
       'South Korea', 'UK', 'France', 'Germany', 'India', 'Denmark',
       'West Germany', 'Iran'], dtype=object)

In [1317]:
df['Country'].value_counts()

Country
USA             59
UK              11
Italy            4
Japan            4
New Zealand      3
France           3
South Korea      2
Germany          2
Brazil           1
Italy1           1
India            1
Denmark          1
West Germany     1
Iran             1
Name: count, dtype: int64

In [1318]:
df['Country'].isna().sum()

np.int64(0)

Content rating - R' 'PG-13' 'Not Rated' 'Approved' nan 'PG' 'Unrated' 'G' handle just those null values

In [1319]:
df['Content Rating'].unique()

array(['R', 'PG-13', 'Not Rated', 'Approved', 'PG', nan, 'Unrated', 'G'],
      dtype=object)

In [1320]:
df[df['Content Rating'].isna()]

,IMBD title ID,Original Title,Release year,Genre,Duration,Country,Content Rating,Director,Income,Votes,Score
27,tt0118799,La vita B9 bella,1997-12-20,"Comedy, Drama, Romance",116,Italy1,NaN,Roberto Benigni,$ 230098753,605.648,8.6
28,tt6751668,Gisaengchung,2019-11-07,"Comedy, Drama, Thriller",132,South Korea,NaN,Bong Joon Ho,$ 257604912,470.931,8.6
36,tt0110413,LÃ©on,1995-04-07,"Action, Crime, Drama",110,France,NaN,Luc Besson,$ 19552639,1.007.598,8.5
40,tt7286456,Joker,2019-10-03,"Crime, Drama, Thriller",122,USA,NaN,Todd Phillips,$ 1074251311,855.097,8.4
41,tt1675434,Intouchables,2012-02-24,"Biography, Comedy, Drama",112,France,NaN,"Olivier Nakache, Ãric Toledano",$ 426588510,736.691,8.4
47,tt0095327,Hotaru no haka,2015-10-11,"Animation, Drama, War",89,Japan,NaN,Isao Takahata,$ 516962,225.438,8.3
48,tt0095765,Nuovo Cinema Paradiso,1988-11-17,Drama,155,Italy,NaN,Giuseppe Tornatore,$ 13826605,223.050,8.3
56,tt4154756,Avengers: Infinity War,2018-04-25,"Action, Adventure, Sci-Fi",149,USA,NaN,"Anthony Russo, Joe Russo",$ 2048359754,796.486,8.2
58,tt4154796,Avengers: Endgame,2019-04-24,"Action, Adventure, Drama",181,USA,NaN,"Anthony Russo, Joe Russo",$ 2797800564,754.786,8.2
62,tt0047396,Rear Window,1955-04-14,"Mystery, Thriller",112,USA,NaN,Alfred Hitchcock,$ 37032034,432.390,8.1
63,tt2380307,Coco,2017-12-28,"Animation, Adventure, Family",105,USA,NaN,"Lee Unkrich, Adrian Molina",$ 807083670,352.455,8.1
65,tt4633694,Spider-Man: Into the Spider-Verse,2018-12-25,"Animation, Action, Adventure",117,USA,NaN,"Bob Persichetti, Peter Ramsey",$ 375540831,335.892,8.1
66,tt1187043,3 Idiots,2009-12-25,"Comedy, Drama",170,India,NaN,Rajkumar Hirani,$ 60262836,332.217,8.1
69,tt0032553,The Great Dictator,1945-06-25,"Comedy, Drama, War",125,USA,NaN,Charles Chaplin,$ 969879,197.381,8.0
70,tt0043014,Sunset Blvd.,1951-06-15,"Drama, Film-Noir",110,USA,NaN,Billy Wilder,$ 299645,195.789,8.0
81,tt0066921,A Clockwork Orange,1972-09-07,"Crime, Drama, Sci-Fi",136,UK,NaN,Stanley Kubrick,$ 26903440,740.301,7.8
86,tt0093058,Full Metal Jacket,1987-10-09,"Drama, War",116,UK,NaN,Stanley Kubrick,$ 46357676,658.175,7.7
89,tt0033467,Citizen Kane,1948-11-25,"Drama, Mystery",119,USA,NaN,Orson Welles,$ 1594107,389.322,7.6
90,tt8579674,1917,2020-01-23,"Drama, War",119,USA,NaN,Sam Mendes,$ 384857224,362.897,7.6
92,tt0052357,Vertigo,1958-11-18,"Mystery, Romance, Thriller",128,USA,NaN,Alfred Hitchcock,$ 7796389,352.786,7.5
93,tt0053125,North by Northwest,1959-10-28,"Adventure, Mystery, Thriller",136,USA,NaN,Alfred Hitchcock,$ 73446,291.628,7.5
98,tt0059578,Per qualche dollaro in piÃ¹,1965-12-20,Western,132,Italy,NaN,Sergio Leone,$ 15000000,226.039,7.4
100,tt0045152,Singin' in the Rain,1953-02-05,"Comedy, Musical, Romance",103,USA,NaN,Stanley Donen,$ 1864182,213.152,7.4

In [1321]:
df['Content Rating'] = df['Content Rating'].fillna('Not Rated')

In [1322]:
df['Content Rating'].isna().sum()

np.int64(0)

director - remoce white spaces and handle them, to standardiezed

In [1323]:
df['Director'].unique()

array(['Frank Darabont', 'Francis Ford Coppola', 'Christopher Nolan',
       'Peter Jackson', 'Sidney Lumet', 'Robert Zemeckis', 'Sergio Leone',
       'Martin Scorsese', 'David Fincher', 'Jonathan Demme',
       'George Lucas', 'Steven Spielberg',
       'Fernando Meirelles, KÃ¡tia Lund', 'Hayao Miyazaki',
       'Roberto Benigni', 'Bong Joon Ho', 'Frank Capra', 'Akira Kurosawa',
       'Ridley Scott', 'Tony Kaye', 'Luc Besson', 'James Cameron',
       'Bryan Singer', 'Roger Allers, Rob Minkoff', 'Todd Phillips',
       'Olivier Nakache, Ã\x89ric Toledano', 'Roman Polanski',
       'Damien Chazelle', 'Alfred Hitchcock', 'Michael Curtiz',
       'Isao Takahata', 'Giuseppe Tornatore', 'Charles Chaplin',
       'Quentin Tarantino', 'Andrew Stanton', 'Stanley Kubrick',
       'Anthony Russo, Joe Russo', 'Chan-wook Park',
       'Lee Unkrich, Adrian Molina', 'Florian Henckel von Donnersmarck',
       'Bob Persichetti, Peter Ramsey', 'Rajkumar Hirani', 'Billy Wilder',
       'Sam Mendes', 'Mel Gibson', 'Richard Marquand', 'Michel Gondry',
       'John Lasseter', 'Gus Van Sant', 'Guy Ritchie', 'Darren Aronofsky',
       'Lee Unkrich', 'Brian De Palma', 'Jean-Pierre Jeunet',
       'Orson Welles', 'Milos Forman', 'Thomas Vinterberg', 'David Lean',
       'George Roy Hill', 'Wolfgang Petersen', 'Asghar Farhadi',
       'Stanley Donen'], dtype=object)

In [1324]:
fixes_director_name= {
    'KÃ¡tia Lund' : 'kaitia Lund',
    'Ã\x89ric Toledano' : 'Eric Toledano'
}
df['Director'] = df['Director'].replace(fixes_director_name)

In [1325]:
df['Director'].unique()

array(['Frank Darabont', 'Francis Ford Coppola', 'Christopher Nolan',
       'Peter Jackson', 'Sidney Lumet', 'Robert Zemeckis', 'Sergio Leone',
       'Martin Scorsese', 'David Fincher', 'Jonathan Demme',
       'George Lucas', 'Steven Spielberg',
       'Fernando Meirelles, KÃ¡tia Lund', 'Hayao Miyazaki',
       'Roberto Benigni', 'Bong Joon Ho', 'Frank Capra', 'Akira Kurosawa',
       'Ridley Scott', 'Tony Kaye', 'Luc Besson', 'James Cameron',
       'Bryan Singer', 'Roger Allers, Rob Minkoff', 'Todd Phillips',
       'Olivier Nakache, Ã\x89ric Toledano', 'Roman Polanski',
       'Damien Chazelle', 'Alfred Hitchcock', 'Michael Curtiz',
       'Isao Takahata', 'Giuseppe Tornatore', 'Charles Chaplin',
       'Quentin Tarantino', 'Andrew Stanton', 'Stanley Kubrick',
       'Anthony Russo, Joe Russo', 'Chan-wook Park',
       'Lee Unkrich, Adrian Molina', 'Florian Henckel von Donnersmarck',
       'Bob Persichetti, Peter Ramsey', 'Rajkumar Hirani', 'Billy Wilder',
       'Sam Mendes', 'Mel Gibson', 'Richard Marquand', 'Michel Gondry',
       'John Lasseter', 'Gus Van Sant', 'Guy Ritchie', 'Darren Aronofsky',
       'Lee Unkrich', 'Brian De Palma', 'Jean-Pierre Jeunet',
       'Orson Welles', 'Milos Forman', 'Thomas Vinterberg', 'David Lean',
       'George Roy Hill', 'Wolfgang Petersen', 'Asghar Farhadi',
       'Stanley Donen'], dtype=object)